### ISSUE TITLE
ublock origin blank page on localhost

### ISSUE THREAD

**Issue by entropyqueen** [agateblue/administrans#10]

**Comment by Ugarz** [comment]
Yes I get this behaviour too!
Do you know what It is required to do to go through the filter, without updating the filter list manually?

**Comment by entropyqueen** [comment]
I looked around for a bit, it appears that when Plausible is blocked on localhost, that crashes the app somehow.

It seems similar to this issue: [https://github.com/vitejs/vite/issues/4797](https://github.com/vitejs/vite/issues/4797)

I'm not sure we can catch the error?

Since it affects only localhost, I think we may just want to tell ppl to deactivate the adblocker for localhost..?
