### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by Ugarz** [agateblue/administrans#14]
Hello 👋🏼 

Should we use a coding style in order to uniformise the way we develop features? this could help us ensure we control data-flow and their types.
- Adds TypeScript support (use `.ts` files, `interfaces` and `types`)
- Eslint / Prettier + editor auto-save trigger formating rules
- eliminate dead code or unused variables

**Comment by agateblue** [comment]
Hello ! At this time, I'm not willing to switch to typescript. We do have linting in place though I always forget to run it, it's available through `yarn lint` and it makes sense to have this applied automatically on save if it's not too much hassle :)

I expect the linting to address your third point by detecting unused code or variables as well.

**Comment by agateblue** [comment]
Fix by #16
